// <auto-generated />
namespace SozialWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VERK2015_H47 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VERK2015_H47));
        
        string IMigrationMetadata.Id
        {
            get { return "201505070045226_VERK2015_H47"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
